server:
  port: 9002

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(n6gjOn8ThLy1v+oZQVTDjQ==)
#    url: ENC(RXHAnaVutkRJnU0erxXMvul98JB6deNac0l/GOA/IHK5fw+M9OIMdenfpLaIrPMvPgOmvm3wzEfV0/4QgZYqYLhHvb4xRzvNFkFT+l00qNWyS9KwYBIt+ERAH/tHi3mgBZ8R+diulX8=)
#    username: ENC(LYAtPaB+Ylt2yjWP8dtAEw==)
    password: ENC(2BhEw5prdiskamEYXfJ8hv3i0EjfI6g5)
  mail:
    host: smtp.qq.com
    username: ENC(RhySMmqywvJZKxWqEEVe9mXsWes2w6Obf+93dCD1zvk=)
    password: ENC(NnPdEuIuxTEzhKXMSuWXhvNW/yR5xFhPqXnMoRO5cws=)
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/files/
  thymeleaf:
    enabled: true
    check-template: true
    suffix: .html
    prefix: classpath:/templates/
  # 返回的api接口的配置，全局有效
  #jackson:
  #default-property-inclusion: non_null #如果某一个字段为null，就不再返回这个字段
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # Redis数据库索引（默认为0）
    database: 0
  # 缓存数据
  cache:
#    type: simple
    type: redis
    cache-names: cacheData
    redis:
      time-to-live: 600000
      use-key-prefix: false
      cache-null-values: off



#jasypt加密的密匙
jasypt:
  encryptor:
    #    3.0.0 之前版本
    #    # 加密所需的salt(盐)
    #    # 加密方式和算法一定要对应一致
    #    # BasicTextEncryptor 对应加密方式：PBEWithMD5AndDES，StrongTextEncryptor 对应加密方式： PBEWithMD5AndTripleDES
    #    # 部署时配置salt(盐)值 java -jar -Djasypt.encryptor.password=1qaz2wsx3edc -Djasypt.encryptor.algorithm=PBEWithMD5AndDES xxx.jar
    #    # 或者在服务器的环境变量里配置,进一步提高安全性
    #    # 打开/etc/profile文件 vim /etc/profile
    #    # 文件末尾插入 export JASYPT_PASSWORD = SALT
    #    # 文件末尾插入 export JASYPT_ALGORITHM = ALGORITHM
    #    # 编译 source /etc/profile
    #    # 运行 java -jar -Djasypt.encryptor.password=${JASYPT_PASSWORD} -Djasypt.encryptor.algorithm=${JASYPT_ALGORITHM} xxx.jar
    #    password: salt
    #    # 默认加密方式PBEWithMD5AndDES,可以更改为PBEWithMD5AndTripleDES
    #    algorithm: PBEWithMD5AndTripleDES
    # 3.0.0 以后
#    password: salt
    # 加密算法设置
#    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


mail:
  # 邮件接收者
  recipient: "1498097245@qq.com"
  fromMail:
    addr: alex9012@qq.com

# 日志级别
logging:
  level:
    root: info
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace

## 开启定时任务
scheduling:
  enabled: false

## 开启数据缓存
caching:
  enabled: true

user:
  export: "F://project//spring-boot-api-scaffold//src/main//resources//files//"
  mac-export: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/files/"
  icon: "F://project//spring-boot-api-scaffold//src/main//resources//icons//"
  mac-icon: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/icons/"


project:
  #  basedir: "F:/project/spring-boot-api-scaffold"
  basedir: "/Users/wangzhao/work/projects/spring-boot-api-scaffold"


# 拉易网
drageasy:
  token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9kcmFnZWFzeS5jb20iLCJhdWQiOiJ2c29udGVyIiwiaWF0IjoxNTk2MTg5MjU3LCJleHAiOjE1OTYxOTI4NTcsInVpZCI6Im9qUG41d0xYNy0zRzB2aFJEdFAtVDdHRWd5S1UifQ.I2vjDyo8bVm8OtmkaTZAqAne9SJn9yRIP0sVP2bPXCo"
  uploadToken: "https://www.drageasy.com/util/getUploadToken"
  uploadPath: "https://www.drageasy.com/util/qiniu_upp"
