
server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: ENC(X5PosLRVcpeW/kjV5vIt8g==)
#    password: ENC(Jcdxj2C4H1ZnNIsuSocyGpx+43A7WlkE)
    username: root
    password: Master@2011
  mail:
    host: smtp.qq.com
    username: 1498097245@qq.com
    password: sputxexvxrgoihef
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/files/
  thymeleaf:
    enabled: true
    check-template: true
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: 127.0.0.1
    port: 6379
    password: master2011
    timeout: 10000

#jasypt加密的密匙
jasypt:
  encryptor:
    # 加密所需的salt(盐)
    # 加密方式和算法一定要对应一致
    # BasicTextEncryptor 对应加密方式：PBEWithMD5AndDES，StrongTextEncryptor 对应加密方式： PBEWithMD5AndTripleDES
    # 部署时配置salt(盐)值 java -jar -Djasypt.encryptor.password=1qaz2wsx3edc -Djasypt.encryptor.algorithm=PBEWithMD5AndDES xxx.jar
    # 或者在服务器的环境变量里配置,进一步提高安全性
    # 打开/etc/profile文件 vim /etc/profile
    # 文件末尾插入 export JASYPT_PASSWORD = SALT
    # 文件末尾插入 export JASYPT_ALGORITHM = ALGORITHM
    # 编译 source /etc/profile
    # 运行 java -jar -Djasypt.encryptor.password=${JASYPT_PASSWORD} -Djasypt.encryptor.algorithm=${JASYPT_ALGORITHM} xxx.jar
    password: 1qaz2wsx3edc
    # 默认加密方式PBEWithMD5AndDES,可以更改为PBEWithMD5AndTripleDES
    algorithm: PBEWithMD5AndTripleDES


mail:
  recipient: "1498097245@qq.com,749856591@qq.com"
  fromMail:
    addr: alex9012@qq.com

# 日志级别
logging:
  level:
    root: info
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace

## 开启定时任务
scheduling:
  enabled: true

user:
  export: "F://project//spring-boot-api-scaffold//src/main//resources//files//"
  mac-export: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/files/"
  icon: "F://project//spring-boot-api-scaffold//src/main//resources//icons//"
  mac-icon: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/icons/"

project:
  #  basedir: "F:/project/spring-boot-api-scaffold"
  basedir: "/Users/wangzhao/work/projects/spring-boot-api-scaffold"
