
server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(zL+TaxRb6Vza8qcPxcu5Lw==)
    password: ENC(2BhEw5prdiskamEYXfJ8hv3i0EjfI6g5)
  mail:
    host: smtp.qq.com
    username: ENC(RhySMmqywvJZKxWqEEVe9mXsWes2w6Obf+93dCD1zvk=)
    password: ENC(NnPdEuIuxTEzhKXMSuWXhvNW/yR5xFhPqXnMoRO5cws=)
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/files/
  thymeleaf:
    enabled: true
    check-template: true
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: 127.0.0.1
    port: 6379
    password: master2011
    timeout: 10000

#jasypt加密的密匙
jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator


mail:
  recipient: "1498097245@qq.com,749856591@qq.com"
  fromMail:
    addr: alex9012@qq.com

# 日志级别
logging:
  level:
    root: info
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace

## 开启定时任务
scheduling:
  enabled: true

user:
  export: "F://project//spring-boot-api-scaffold//src/main//resources//files//"
  mac-export: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/files/"
  icon: "F://project//spring-boot-api-scaffold//src/main//resources//icons//"
  mac-icon: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/icons/"

project:
  #  basedir: "F:/project/spring-boot-api-scaffold"
  basedir: "/Users/wangzhao/work/projects/spring-boot-api-scaffold"
