
server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: admin
#    password: master2011
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ENC(X5PosLRVcpeW/kjV5vIt8g==)
    password: ENC(Jcdxj2C4H1ZnNIsuSocyGpx+43A7WlkE)
  mail:
    host: smtp.qq.com
    username: 1498097245@qq.com
    password: sputxexvxrgoihef
  resources:
    static-locations: classpath:/resources/,classpath:/static/,classpath:/templates/,classpath:/files/
  thymeleaf:
    enabled: true
    check-template: true
    suffix: .html
    prefix: classpath:/templates/
  redis:
    host: 104.224.178.5
    port: 6379
    password: ENC(Q23otvRVfrM8xUyIhMCK02GjYQo812Kt)
    timeout: 10000

## 开启定时任务
scheduling:
  enabled: true

mail:
  fromMail:
    addr: alex9012@qq.com

# 日志级别
logging:
  level:
    root: info
    com.scaffold.test.mapper: trace
    com.scaffold.test.task: trace


user:
  export: "F://project//spring-boot-api-scaffold//src/main//resources//files//"
  mac-export: "/Users/wangzhao/work/projects/spring-boot-api-scaffold/src/main/resources/files/"

project:
  #  basedir: "F:/project/spring-boot-api-scaffold"
  basedir: "/Users/wangzhao/work/projects/spring-boot-api-scaffold"